MLK-22505 mx7ulp: Enable UUU support for mx7ulp_evk_m4boot_defconfig target
Currently it's not possible to boot mx7ulp_evk_m4boot_defconfig target:

  OBJCOPY examples/standalone/hello_world.bin
  LD      u-boot
arch/arm/lib/built-in.o: In function `setup_serial_tag':
/home/breno/NXP/bootloader/uboot-imx/arch/arm/lib/bootm.c:192: \
undefined reference to `get_board_serial'
Makefile:1505: recipe for target 'u-boot' failed
make: *** [u-boot] Error 1

Fix this issue by enabling UUU support for mx7ulp_evk_m4boot_defconfig target.

Reviewed-by: Ye Li <ye.li@nxp.com>
Signed-off-by: Breno Lima <breno.lima@nxp.com>
(cherry picked from commit 7fab9bf1bbcaa93f91cd69c970e92676011a47d3)